Ignore clippy warnings about complex types
One of the new functions in PKCS#11 3.2 have 10(!) arguments, which goes
over the threshold of what clippy considers reasonable. But given that
we need to be compatible with this API, there is no other reasonable way
to tackle this than to ignore the warning/error.

error: very complex type used. Consider factoring parts into `type` definitions
    --> /home/runner/work/rust-cryptoki/rust-cryptoki/cryptoki-sys/src/bindings/x86_64-unknown-linux-gnu.rs:6801:35
     |
6801 |       pub C_UnwrapKeyAuthenticated: Result<
     |  ___________________________________^
6802 | |         unsafe extern "C" fn(
6803 | |             arg1: CK_SESSION_HANDLE,
6804 | |             arg2: *mut CK_MECHANISM,
...    |
6814 | |         ::libloading::Error,
6815 | |     >,
     | |_____^
     |

Signed-off-by: Jakub Jelen <jjelen@redhat.com>